name: City Website Deployment

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  deploy-city-websites:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Install Required Python Libraries
      run: |
        pip install PyGithub requests

    - name: 4. Create new.txt with test cities (if doesn't exist)
      run: |
        if [ ! -f new.txt ]; then
          echo "Creating new.txt with sample cities..."
          cat > new.txt << EOF
Dallas
Austin
Houston
EOF
        fi
        echo "Contents of new.txt:"
        cat new.txt

    - name: 5. Run City Deployer Script
      run: python new_website_deployer.py
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 6. Debug Information
      if: ${{ inputs.debug }}
      run: |
        echo "Workflow completed"
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Checking if Python file exists:"
        if [ -f new_website_deployer.py ]; then
          echo "✓ new_website_deployer.py exists"
        else
          echo "✗ new_website_deployer.py not found"
        fi
        if [ -f new.txt ]; then
          echo "✓ new.txt exists"
          echo "Contents:"
          cat new.txt
        else
          echo "✗ new.txt not found"
        fi
