name: City Website Deployment

on:
  workflow_dispatch:

jobs:
  deploy-city-websites:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python Libraries
      run: pip install PyGithub requests

    - name: Verify required files exist
      run: |
        echo "Checking for required files:"
        ls -la
        if [ ! -f new_website_deployer.py ]; then
          echo "ERROR: new_website_deployer.py not found!"
          exit 1
        fi
        if [ ! -f new.txt ]; then
          echo "ERROR: new.txt not found!"
          exit 1
        fi
        echo "All required files found"
        echo "Cities to deploy:"
        cat new.txt

    - name: Run Deployment Script
      run: python new_website_deployer.py
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
