name: Final City Deployment Solution (Manual Only)

on:
  # This is the ONLY trigger. The workflow will ONLY run when manually selected.
  workflow_dispatch: 

permissions:
  # Grant write permissions to the runner environment to prevent subprocess errors.
  contents: write 
  pages: none    
  id-token: none 

jobs:
  dynamic_repo_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository (Using NEW7 Token)
        uses: actions/checkout@v4
        with:
          # Your custom PAT token is used here
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Creates and Pushes New Repos)
        run: python new_website_deployer.py
