name: New Manual City Website Deployer Duplicate

on:
  # Allows the workflow to be triggered manually from the GitHub UI
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    # Required permission settings for creating new repositories
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # --- UPDATED: Install NEW Required Python Libraries ---
    - name: 3. Install Required Python Libraries
      # Added 'wikipedia' for function 7 and 'geopy' for function 1
      run: pip install PyGithub requests wikipedia geopy
      
    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        # REFERENCE TO THE NEW SECRET
        GH_TOKEN: ${{ secrets.new7 }}
        # Set the required delay between repo creations (in seconds)
        DEPLOY_DELAY: 200 # Increased slightly for API calls
      # Ensure the script name matches the assumption from the provided code
      run: python new_website_updater.py
