name: Deploy City Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub requests
        
    - name: Create city file
      run: |
        echo "Nashville" > new.txt
        
    - name: Deploy website
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python new_website_deployer.py
        
    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      if: always()
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
