# .github/workflows/new_website_deployer.yml

[cite_start]name: New Manual City Website Deployer Duplicate [cite: 42]

on:
  # Allows the workflow to be triggered manually from the GitHub UI
  [cite_start]workflow_dispatch: [cite: 42]

jobs:
  create-and-deploy-all-repos:
    [cite_start]runs-on: ubuntu-latest [cite: 42]
    
    # Required permission settings for creating new repositories and pages
    permissions:
      contents: write
      pages: write
      [cite_start]id-token: write [cite: 42]

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        [cite_start]fetch-depth: 0 [cite: 43]

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        [cite_start]python-version: '3.x' [cite: 43]

    - name: 3. Install Required Python Libraries
      # Installs PyGithub, requests, and the new 'wikipedia-api'
      run: pip install PyGithub requests wikipedia-api
      
    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        # [cite_start]Passes the required GitHub Personal Access Token [cite: 44]
        GH_TOKEN: ${{ secrets.new7 }}
        # Passes the Google API Key (Must be set in GitHub secrets to avoid skipping dynamic content)
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        # [cite_start]Set the required delay between repo creations (in seconds) [cite: 44]
        DEPLOY_DELAY: 180 
      run: python new_website_updater.py
