# .github/workflows/deploy.yml

[cite_start]name: New Manual City Website Deployer Duplicate [cite: 42]

on:
  [cite_start]workflow_dispatch: [cite: 42]

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      [cite_start]id-token: write [cite: 42]

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        [cite_start]fetch-depth: 0 [cite: 43]

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      # Added 'wikipedia-api' for fetching city descriptions
      run: pip install PyGithub requests wikipedia-api

    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        # This secret must be created in your repository settings
        [cite_start]GH_TOKEN: ${{ secrets.new7 }} [cite: 44]
        # NEW: Add your Google API key as a secret named GOOGLE_API_KEY
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DEPLOY_DELAY: 180
      run: python new_website_updater.py
