name: New Manual City Website Deployer Duplicate

on:
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      # Installs PyGithub, requests, wikipedia, and geopy (REQUIRED for Function 1 geolocation)
      run: pip install PyGithub requests wikipedia geopy
      
    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        GH_TOKEN: ${{ secrets.new7 }} 
        DEPLOY_DELAY: 200 
      run: python new_website_updater.py
