name: Deploy City Website

on:
  workflow_dispatch:  # Manual trigger only - NO AUTO WORKFLOWS!
    inputs:
      city_override:
        description: 'Optional: Override city name (leave blank to use new.txt)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Set timeout for the job
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub==2.1.1 requests==2.31.0
        echo "✓ Dependencies installed"
        
    - name: Create city file if override provided
      if: ${{ github.event.inputs.city_override != '' }}
      run: |
        echo "${{ github.event.inputs.city_override }}" > new.txt
        echo "✓ Using override city: ${{ github.event.inputs.city_override }}"
        
    - name: Display city to be deployed
      run: |
        echo "📍 City to deploy:"
        cat new.txt
        echo ""
        
    - name: Run deployment script
      env:
        GH_TOKEN: ${{ secrets.NEW7 }}
      run: |
        echo "================================================"
        echo "🚀 STARTING EYE TRY A.I. CITY WEBSITE DEPLOYMENT"
        echo "================================================"
        python new_website_deployer.py
        
    - name: Display deployment summary
      if: always()
      run: |
        echo ""
        echo "================================================"
        echo "📋 DEPLOYMENT SUMMARY"
        echo "================================================"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "================================================"
        echo ""
        echo "ℹ️ Check the logs above for deployment status."
        echo "ℹ️ New repository should appear in your GitHub account."
        echo "ℹ️ GitHub Pages may take 5-10 minutes to activate."
        echo ""
        echo "📚 ATTRIBUTION & CITATIONS:"
        echo "   • Wikipedia/Wikimedia Foundation - City information"
        echo "   • OpenStreetMap contributors & Nominatim - Location data"
        echo "   • Open-Meteo.com - Weather forecast data"
        echo "   • Overpass API/OpenStreetMap - Local business data"
        echo "================================================"
