# .github/workflows/new_website_deployer.yml - The Final, Corrected Version

name: Official GitHub Pages Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. Build job: Runs your Python script and packages the files
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # This runs your existing Python script
      - name: 3. Run City/State Replacement Script
        run: python new_website_deployer.py
        
      # Upload the modified files to be deployed in the next step
      - name: 4. Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # Use the root directory

  # 2. Deploy job: Pushes the artifact live
  deploy:
    # --- FIX: REMOVED the 'environment' block that was causing the protection error. ---
    runs-on: ubuntu-latest
    needs: build
    # These permissions are required for the official GitHub Pages action to work.
    permissions:
      pages: write
      id-token: write
    steps:
      - name: 5. Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
