name: New Manual City Website Deployer Duplicate

on:
  # Allows the workflow to be triggered manually from the GitHub UI
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    # Required permission settings for creating new repositories
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      run: pip install PyGithub requests
      
    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        # REFERENCE TO THE NEW SECRET
        GH_TOKEN: ${{ secrets.new7 }}
        # Set the required delay between repo creations (in seconds)
        DEPLOY_DELAY: 180 
      run: python new_website_updater.py
