name: Deploy New City Website

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Type "DEPLOY" to confirm new repository creation'
        required: true
        default: 'DEPLOY'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Verify deployment confirmation
      if: ${{ github.event.inputs.confirm_deployment != 'DEPLOY' }}
      run: |
        echo "Error: You must type 'DEPLOY' to confirm deployment"
        exit 1
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub
        
    - name: Validate new.txt file
      run: |
        if [ ! -f "new.txt" ]; then
          echo "Error: new.txt file not found"
          exit 1
        fi
        CONTENT=$(cat new.txt)
        if [[ ! "$CONTENT" =~ ^[A-Za-z]+-[A-Za-z]+$ ]]; then
          echo "Error: new.txt must contain city-state format like 'Dallas-Texas'"
          exit 1
        fi
        echo "Valid city-state format: $CONTENT"
        
    - name: Deploy new city website
      env:
        GITHUB_TOKEN: ${{ secrets.NEW7 }}
      run: |
        python new_website_deployer.py
        
    - name: Check deployment status
      run: |
        if [ -f "deployment_success.txt" ]; then
          echo "✅ Deployment successful!"
          cat deployment_success.txt
        elif [ -f "deployment_error.txt" ]; then
          echo "❌ Deployment failed!"
          cat deployment_error.txt
          exit 1
        else:
          echo "⚠️  Unknown deployment status"
          exit 1
          
    - name: Cleanup status files
      if: always()
      run: |
        rm -f deployment_success.txt deployment_error.txt
        
    - name: Archive deployment log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: deployment-log
        path: |
          new.txt
        retention-days: 1
