name: Dynamic City Repo Creator (Manual-Only Guarantee)

on:
  # 🛑 CRITICAL FIX: Only the manual trigger is listed. 
  # This guarantees no other event (like push or schedule) can start the workflow.
  workflow_dispatch: 

permissions:
  # Minimal permissions for the runner.
  contents: none
  pages: none    
  id-token: none 

jobs:
  # ----------------------------------------------------------------
  # JOB 1: EXECUTE SCRIPT AND PUSH NEW REPO
  # ----------------------------------------------------------------
  dynamic_repo_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          # Use the NEW7 PAT token to grant cross-repository permissions
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Creates and Pushes New Repos)
        run: python new_website_deployer.py
