name: Dynamic City Website Deployment (Manual Only)

on:
  # 🛑 Only manual triggering is enabled now.
  workflow_dispatch: 

permissions:
  # Necessary permissions are retained
  contents: read
  pages: write    
  id-token: write 

jobs:
  # ----------------------------------------------------------------
  # JOB 1: BUILD & DEPLOY TO DYNAMIC REPOS
  # ----------------------------------------------------------------
  dynamic_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (Full History)
        uses: actions/checkout@v4
        with:
          # Use the NEW7 PAT for cloning/pushing across repos
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Handles Dynamic Repo Creation/Push)
        # Your script runs the logic here, including the cross-repo pushes.
        run: python new_website_deployer.py

      # --- Deployment for the current 'O-2' repo (Standard GitHub Pages) ---
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Current Artifact (index.html, new.txt, etc.)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' 

  # ----------------------------------------------------------------
  # JOB 2: DEPLOY (Standard O-2 Repo Pages Deployment)
  # ----------------------------------------------------------------
  deploy_o2_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest
    needs: dynamic_deploy 
    steps:
      - name: Deploy to GitHub Pages (O-2 Repo)
        id: deployment
        uses: actions/deploy-pages@v4
