name: Deploy City Website

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Added pyyaml and jinja2 as a best-practice future-proofing step
        pip install PyGithub requests PyYAML jinja2 
        
    - name: Run deployment script
      env:
        # Use the secret name as defined in your instructions
        GH_TOKEN: ${{ secrets.NEW7 }} 
      run: |
        python new_website_deployer.py
