name: City Website Deployer

on:
  # Allows the workflow to be triggered manually from the GitHub UI
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    # Required permission settings for creating new repositories
    permissions:
      contents: write
      pages: write
      id-token: write
      repositories: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      run: pip install PyGithub requests
      
    - name: 4. Run City Deployment Script
      env:
        # GitHub token for repository operations
        GH_TOKEN: ${{ secrets.new7 }}
        # Set the required delay between repo creations (in seconds)
        DEPLOY_DELAY: 180 
      run: python new_website_updater.py

    - name: 5. Verify Deployment Completion
      run: |
        echo "City deployment script execution completed."
        echo "Check the logs above for any errors."
        echo "If repositories were created successfully, they should be available in your GitHub account."
