name: Dynamic City Repo Creator (Final Guaranteed Workflow)

on:
  # 🛑 Only the manual trigger is listed.
  workflow_dispatch: 
  
permissions:
  # CRITICAL: Grant the default GITHUB_TOKEN write access. 
  # This often solves permission-related issues for subprocess/git commands running inside the action.
  contents: write
  pages: none    
  id-token: none 

jobs:
  # ----------------------------------------------------------------
  # JOB 1: EXECUTE SCRIPT AND PUSH NEW REPO
  # ----------------------------------------------------------------
  dynamic_repo_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository (Using NEW7 Token)
        uses: actions/checkout@v4
        with:
          # Use the NEW7 PAT token to grant cross-repository permissions 
          # to the Python script execution environment.
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Creates and Pushes New Repos)
        # This executes your script. The script handles all the heavy lifting 
        # of creating the new repo, pushing files, and activating GitHub Pages.
        run: python new_website_deployer.py
