name: Deploy City Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests Jinja2

      - name: Run deployment script
        env:
          GH_TOKEN: ${{ secrets.NEW7 }}
        run: |
          python new_website_deployer.py
