name: Dynamic City Website Builder (Manual Only)

on:
  # 🛑 Only manual triggering is allowed.
  workflow_dispatch: 

permissions:
  # Minimal permissions for the runner; the secrets.NEW7 token handles the heavy lifting
  contents: none
  pages: none    
  id-token: none 

jobs:
  # ----------------------------------------------------------------
  # JOB 1: BUILD & DEPLOY TO DYNAMIC REPOS ONLY
  # This job executes the script responsible for creating new repos and nothing else.
  # ----------------------------------------------------------------
  dynamic_repo_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (Full History)
        uses: actions/checkout@v4
        with:
          # IMPORTANT: Use the NEW7 PAT token for all Git operations to enable 
          # creation and pushing to new, city-named repositories.
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Creates and Pushes New Repos)
        # This script ('new_website_deployer.py') must be entirely responsible 
        # for reading new.txt, updating index.html, and creating/pushing 
        # the new city-specific repository.
        run: python new_website_deployer.py

# 🛑 NO SECOND JOB. NO 'pages: write' PERMISSION. NO deployment of the current O-2 repo.
