name: Dynamic City Repo Creator (Final Manual Workflow)

on:
  # 🛑 This is the ONLY trigger. The workflow will ONLY run when manually selected.
  workflow_dispatch: 

permissions:
  # Minimal permissions for the runner. The secrets.NEW7 token handles the heavy lifting.
  contents: none
  pages: none    
  id-token: none 

jobs:
  # ----------------------------------------------------------------
  # JOB 1: EXECUTE SCRIPT AND PUSH NEW REPO
  # ----------------------------------------------------------------
  dynamic_repo_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          # CRITICAL: Use the NEW7 PAT token to grant cross-repository permissions
          token: ${{ secrets.NEW7 }} 
          fetch-depth: 0 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install requests

      - name: Execute Python Script (Creates and Pushes New Repos)
        # This executes your script which is responsible for API/Git commands
        # to create a new GitHub repo based on the name in new.txt.
        run: python new_website_deployer.py

# 🛑 END OF WORKFLOW. No further steps are needed.
