name: New Manual City Website Deployer

on:
  # Allows the workflow to be triggered manually from the GitHub UI
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    # Required permission settings for creating new repositories
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      # PyGithub for repo management, requests for all API calls (OSM, Overpass, Wikidata, NOAA)
      run: pip install PyGithub requests
      
    - name: 4. Run City Deployer Script
      run: python new_website_deployer.py
      env:
        # Your GitHub Personal Access Token (PAT)
        # This token is used by PyGithub to create repos and commit files.
        GH_TOKEN: ${{ secrets.new7 }}
