name: Deploy City Website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests
      
      - name: Run deployment script
        env:
          GITHUB_TOKEN: ${{ secrets.NEW7 }}
        run: |
          python new_website_deployer.py
