# new_website_deployer.yml

name: Single-Step Website Deployment

on:
  push:
    branches:
      - main
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # This runs your existing Python script to perform the text replacement
      - name: 3. Run City/State Replacement Script
        run: python new_website_deployer.py
        
      # This deploys the modified files using your new token
      - name: 4. Deploy to GitHub Pages using NEW7
        uses: peaceiris/actions-gh-pages@v4 
        with:
          # Your specified Secret
          github_token: ${{ secrets.NEW7 }} 
          # The source folder for deployment (the root of your repo)
          publish_dir: . 
          # The target branch for GitHub Pages
          publish_branch: gh-pages
          # This ensures the 'gh-pages' branch is created cleanly if missing
          force_orphan: true
