GitHub Pages Jekyll
By GitHub Actions

GitHub Pages Jekyll logo
Package a Jekyll site with GitHub Pages dependencies preinstalled.

Static HTML
By GitHub Actions

Static HTML logo
Deploy static files in a repository without a build.
